App/App/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('main/', views.main, name = 'main'),
    path('main/delete_appointment/<int:appointment_id>', views.delete_appointment, name = 'delete_appointment'),
    path('main/appointments/', views.appointments, name = 'appointments'),
    path('main/ia', views.ia, name = 'ia')
]

App/main/models.py
from django.db import models


# Create your models here.
class Master(models.Model):
    name = models.CharField('name', max_length=100)
    timetable = models.TextField('timetable')
    phone_number = models.CharField('phone_number', max_length=100)

    def get_weekday(self, num):
        return [i.split(',') for i in str(self.timetable).split(";")][num]


class Appointment(models.Model):
    owner_name = models.CharField('owner_name', max_length=100)
    date = models.DateTimeField('Date')
    master_name = models.ForeignKey(Master, on_delete=models.CASCADE)

App/main/views.py
import requests
from django.shortcuts import render
from .models import Master, Appointment
# Create your views here.
from datetime import date, datetime, timedelta
from openai import OpenAI


def main(request):
    #del request.session['appointments']
    try:
        print(request.session['appointments'])
    except:
        request.session['appointments'] = []
    if request.method == 'GET':
        all_masters = Master.objects.all()
        today = datetime.today()
        date_ = str(datetime(today.year, today.month, today.day))
        date_ = date_[0:date_.find(' ')].split('-')
        all_weeks = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        d1 = date(int(date_[0]), int(date_[1]), int(date_[2]))
        d2 = date(int(date_[0]) + 1, int(date_[1]), int(date_[2]))
        delta = d2 - d1  # returns timedelta
        final_data = {}
        timings = {}
        for master in all_masters:
            master_name = master.name
            master_time = [i.split(',') for i in master.timetable.split(";")]
            timings[master_name] = master_time
        data_dynamic = []
        for _ in range(today.weekday()):
            data_dynamic.append(f'  -{all_weeks[today.weekday()].split("-")[0]}-{timings}')
        all_months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
                      'November', 'December']
        for i in range(delta.days + 1):
            day = d1 + timedelta(days=i)
            weekday = day.weekday()
            curr_day = str(day).split("-")[2]
            if curr_day == '01' and len(data_dynamic) > 1:
                month_year = f"{all_months[int(str(day).split('-')[1]) - 2]}-{str(d1 + timedelta(days=i - 1)).split('-')[0]}"
                final_data[month_year] = data_dynamic
                new_data = []
                for _ in range(len(data_dynamic) % 7):
                    new_data.append(f'  -{all_weeks[weekday].split("-")[0]}-{timings}')
                data_dynamic = [i for i in new_data]
            else:
                pass
            data_dynamic.append(f'{curr_day}-{all_weeks[weekday].split("-")[0]}-{timings}')

        return render(request, 'main/index.html',
                      {'all_masters': all_masters, 'final_data': final_data, 'timings': timings,
                       'all_weeks': all_weeks})
    else:
        all_masters = Master.objects.all()
        today = datetime.today()
        date_ = str(datetime(today.year, today.month, today.day))
        date_ = date_[0:date_.find(' ')].split('-')
        all_weeks = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        d1 = date(int(date_[0]), int(date_[1]), int(date_[2]))
        d2 = date(int(date_[0]) + 1, int(date_[1]), int(date_[2]))
        delta = d2 - d1  # returns timedelta
        final_data = {}
        timings = {}
        for master in all_masters:
            master_name = master.name
            master_time = [i.split(',') for i in master.timetable.split(";")]
            timings[master_name] = master_time
        data_dynamic = []
        for _ in range(today.weekday()):
            data_dynamic.append(f'  -{all_weeks[today.weekday()].split("-")[0]}-{timings}')
        all_months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
                      'November', 'December']
        for i in range(delta.days + 1):
            day = d1 + timedelta(days=i)
            weekday = day.weekday()
            curr_day = str(day).split("-")[2]
            if curr_day == '01' and len(data_dynamic) > 1:
                month_year = f"{all_months[int(str(day).split('-')[1]) - 2]}-{str(d1 + timedelta(days=i - 1)).split('-')[0]}"
                final_data[month_year] = data_dynamic
                new_data = []
                for _ in range(len(data_dynamic) % 7):
                    new_data.append(f'  -{all_weeks[weekday].split("-")[0]}-{timings}')
                data_dynamic = [i for i in new_data]
            else:
                pass
            data_dynamic.append(f'{curr_day}-{all_weeks[weekday].split("-")[0]}-{timings}')
        owner_name = request.POST['owner_name']
        master_name = request.POST['master_name']
        master = Master.objects.get(name=master_name)
        month = request.POST['month']
        year = request.POST['year']
        timing = request.POST['select_time'].replace(' ', '')
        new_time = datetime.strptime(timing, '%I:%M%p').strftime("%H:%M")
        dayOfMonth = request.POST['dayOfMonth']
        weekday = request.POST['weekday']
        try: print(Appointment.objects.get(date=f'{year}-{month}-{dayOfMonth} {new_time}'))
        except:
            a = Appointment(master_name=master, date=f"{year}-{month}-{dayOfMonth} {new_time}", owner_name=owner_name)
            a.save()
            a = Appointment.objects.get(date=f"{year}-{month}-{dayOfMonth} {new_time}")
            appointment = [a.id, master_name, f"{year}-{month}-{dayOfMonth} {new_time}"]
            request.session['appointments'].append(appointment)
            return render(request, 'main/index.html',
                          {'all_masters': all_masters, 'final_data': final_data, 'timings': timings,
                           'all_weeks': all_weeks})
        return render(request, 'main/busy.html')

def appointments(request):
    try:
        print(request.session['appointments'])
    except:
        request.session['appointments'] = []
    appointments = request.session['appointments']
    return render(request, 'main/appointments.html', {'appointments': appointments})


def delete_appointment(request, appointment_id):
    Appointment.objects.get(id=appointment_id).delete()
    a = [request.session['appointments'].index(i) for i in request.session['appointments'] if i[0] == appointment_id]
    del request.session['appointments'][a[0]]
    appointments = request.session['appointments']
    return render(request, 'main/appointments.html', {'appointments': appointments})


def ia(request):
    if request.method == 'GET':
        return render(request, 'main/ia.html', {})
    else:
        
        return render(request, 'main/ia.html', {})

App/templates/main/appointments.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'main/css/appointments.css'%} ">
{% endblock %}

{% block content %}
    <main>
        <div class="container">
            <div class="appointments">
                {% for a in appointments %}
                    <div class="appointment">
                        <div class="appointment_info">
                            {% for i in a|slice:"1:" %}
                                {{i}}
                            {% endfor %}
                        </div>
                        <a href="{% url 'main:delete_appointment' a.0 %}">cancel</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

App/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    {% block style %}{% endblock %}
</head>
<body>
    <header id = "header">
           <div class="container">
               <div class="header">
                    <div class="top_header">
                        <div class="phrase">
                            <h1>Serene Steps Yoga</h1>
                        </div>
                        <a href="{% url 'main:main' %}" class = "logo"><img src="{% static 'main/img/logo/logo.jpg' %}" alt="logo"></a>
                        <div class="right_side">
                            <a href="{% url 'main:appointments' %}" class="appointments">My classes</a>
                            <a href="#" class="phone_number">+971505905050</a>
                        </div>
                        <div class="header_burger"><span></span></div>
                    </div>
                    <div class="bottom_header">
                        <nav class = "navbar">
                            <ul class="nav_list">
                                <li class="list_item"><a href="{% url 'main:main' %}">Home</a></li>
                                <li class="list_item"><a href="#section2">About us</a></li>
                                <li class="list_item"><a href="#section3">Location</a></li>
                                <li class="list_item"><a href="#section4">Reviews</a></li>
                            </ul>
                            <a href="#" class="phone_number_media">+971505905050</a>
                            <a href="{% url 'main:appointments' %}" class="appointments_media">My classes</a>
                        </nav>
                    </div>
               </div>
           </div>
    </header>
    {% block content %}

    {% endblock %}

    <footer id = "footer">
        <div class="container">
            <div class="footer_social">
                <a href="#"><img src="{% static 'main/img/icons/instagram.png' %}" alt="img"></a>
                <a href="#"><img src="{% static 'main/img/icons/whatsapp.png' %}" alt="img"></a>
            </div>
            <ul class = "footer_list">
                <li class="list_item"><a href="#section1">Home</a></li>
                <li class="list_item"><a href="#section2">About us</a></li>
                <li class="list_item"><a href="#section4">Location</a></li>
                <li class="list_item"><a href="#section5">Reviews</a></li>
            </ul>
            <div class="footer_copyright">
                Copyright © 2020–2023 stretching.com All rights reserved.
            </div>
        </div>
    </footer>
    <script src = "{% static 'main/js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>

App/templates/main/busy.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
  <h1>Busy slot, try other time</h1>
</body>
</html>

App/templates/main/ia.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="{% url 'main:ia' %}" method = 'POST' id = 'generate'>
  {% csrf_token %}
  <select name="subjects" id="subjects">
    <option value="Math">Math</option>
    <option value="Math">CS</option>
    <option value="Math">Physics</option>
    <option value="Math">Biology</option>
    <option value="Math">Chemistry</option>
    <option value="Math">Business</option>
    <option value="Math">Economy</option>
    <option value="Math">Global Politics</option>
    <option value="Math">History</option>
    <option value="Math">Geograpy</option>
    <option value="Math">Psychology</option>
  </select>
  <input type="text" name = 'topic'>
  <button type = 'submit' class = 'generate'>Generate</button>
</form>
</body>
</html>

App/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'main/css/index.css'%} ">
{% endblock %}
{% block content %}
    <main>
        <div class="container">
            <section id="booking">
                <div class="booking_content">
                    <div class="booking">
                         {% for master in all_masters %}
                             <div class="master">
                                 <h4>{{ master.name }}</h4>
                                 <a href="#" id="{{master.name}}">Book a class</a>
                             </div>
                         {% endfor %}
                    </div>
                    <div class="calendar">
                        <div class="close"><img src="{% static 'main/img/icons/plus.png' %}" alt="img"></div>
                        <div class="timetable">

                            <ul class="days">
                                <li class="day">Monday</li>
                                <li class="day">Tuesday</li>
                                <li class="day">Wednesday</li>
                                <li class="day">Thursday</li>
                                <li class="day">Friday</li>
                                <li class="day">Saturday</li>
                                <li class="day">Sunday</li>
                            </ul>
                            {% for k,v in final_data.items %}
                                 <div class="year_month">
                                    {{k}}
                                 </div>
                                 <hr class="hr">
                                    {% for a in v %}
                                     <a href="#" id="{{k}}-{{a}}" class="date_day">{{ a|slice:"0:2" }}</a>
                                    {% endfor %}
                            {% endfor %}
                        </div>
                    </div>

                    <form action="{% url 'main:main' %}" id="timings" method="POST">
                        {% csrf_token %}

                        <div class="form">

                        </div>
                        <select name="select_time" class="select_form">

                        </select>
                        <button type='submit' class="book_btn">Book</button>
                    </form>
                    <p class="intro_desc">Step into Serene Steps Yoga and embark on a journey to tranquility. Our studio is not just a place for yoga; it's a space where you can find balance, connect with your breath, and cultivate a sense of inner peace. Join us and discover why Serene Steps Yoga is more than just a class; it's a path to a healthier, more serene way of life.</p>
                </div>
                <div class="intro_image">
                    <img src="{% static 'main/img/stretching.jpg' %}" alt="img">
                </div>
            </section>
            <section id="section2">
                <div class="container">
                    <div class="about_us">
                        <div class="about_us_text">
                            <h2>About us</h2>
                            <p class = "main_text">Welcome to Serene Steps Yoga, a sanctuary in the heart of Dubai where the transformative power of yoga unfolds. Rooted in the belief that yoga is more than just a physical practice, we are committed to fostering a holistic approach to wellness. Our philosophy centres around the integration of breath, movement, and mindfulness, guiding our students on a journey to harmonize mind, body, and spirit.
At Serene Steps Yoga our team of dedicated instructors is the heartbeat of our community.Discover the joy of yoga and unlock the potential for a healthier, more balanced life. We look forward to being part of your yoga journey at Serene Steps Yoga.</p>
                        </div>
                        <div class="about_us_carousel">
                            <div id="carouselExampleFade" class="carousel slide carousel-fade">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img src="https://images.squarespace-cdn.com/content/v1/53691b92e4b0cccc5fa97bdb/fe16afba-809e-4136-a4f0-e27daf225b7e/stretching.jpg" class="d-block w-100" alt="img">
                                    </div>
                                    <div class="carousel-item active">
                                        <img src="https://www.shape.com/thmb/ls28gdtp4-wR5w__85zsxCG8Emc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/6-Stretches-You-Should-Try-Doing-88a7ab6ef83e493f9b74770d15913c41.jpg" class="d-block w-100" alt="img">
                                    </div>
                                </div>
                                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section id="section3">
                <div class="container">
                    <div class='map_details'>
                        <div class="map">
                            <h3>Location</h3>
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3613.671119122872!2d55.13544417537793!3d25.07913377778725!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f6b85a7a78d2f%3A0x154e4958aa77d693!2sYoga%20House%20-%20Intercontinental%20Marina!5e0!3m2!1sen!2sae!4v1701437126407!5m2!1sen!2sae" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                </div>
            </section>
            <section id="section4">
                <div class="container">
                    <div class="outerdiv">

                        <div class="innerdiv">
                          <!-- div1 -->
                          <div class="div1 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name">Faranak h_n</p>
                              </div>
                            </div>
                            <div class="review">
                            <p>“ mostly I carry my bags with the right hand so my shoulders were so tired and there was no balance one of them was down also when i was trying to stand straight my back was tired so i tried their service and it was helpful.”</p>
                            </div>
                          </div>
                          <!-- div2 -->
                          <div class="div2 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name">Sally Elazab</p>
                              </div>
                            </div>
                            <div class="review">
                            <p>“Amazing place, new and different experience, changes happens from first session. I loved their staff, so friendly and professional.”</p>
                            </div>
                          </div>
                          <!-- div3 -->
                          <div class="div3 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name dark">Ralph Boyz</p>
                              </div>
                            </div>
                            <div class="review dark">
                              <p>“ I’ve been struggling with my face muscles since I had Bell’s Palsy a few years ago. I decided to try out the face massage they have it and it was amazing. I’ll need more sessions to fully recover, but I really enjoyed the results. Also the day after my skin was super tight and my face macules was super pumped, it feel like a face lift. The Dr is very knowledgeable and in definitely coming back. ”</p>
                            </div>
                          </div>
                          <!-- div4 -->
                          <div class="div4 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name dark">Lena Sami</p>
                              </div>
                            </div>
                            <div class="review dark">
                            <p>“ Loved my appointment with this clinic, they really worked on my posture and gave me a lot of advice on how to fix it ”</p>
                            </div>
                          </div>
                          <!-- div5 -->
                          <div class="div5 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name">Nisreen Sherbatji</p>
                              </div>
                            </div>
                            <div class="review">
                            <p>“ It was an amazing experience
                                They heal the body in a comfortable way
                                I love it and i will come back to them 😍♥️ ”</p>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
{% endblock %}